model:
  embeddings_features: 2
  embeddings_hidden: 10
  train: true
  seed: 29
  epochs: 600
  lr: 0.003
  visualize: false

dataset:
  batch_size: -1

defaults:
  - _self_
  - /output: default_output
  - /model: default_model

hydra:
  job:
    chdir: true
  run:
    dir: ./outputs/${model.name}_${dataset.name}_${loss.name}_${now:%Y-%m-%d}/${now:%H-%M-%S}
# tensorflow