model:
  name: default_model
  embeddings_features: 2
  embeddings_hidden: 10
  train: true
  seed: 29
  epochs: 300
  lr: 0.003

loss:
  name: MSE_loss

dataset:
  name: synthetic_gaussian
  batch_size: -1

defaults:
  - _self_
  - /output: default_output

hydra:
  job:
    chdir: true
  run:
    dir: ./outputs/${model.name}_${dataset.name}_${loss.name}_${now:%Y-%m-%d}/${now:%H-%M-%S}
# tensorflow